### ISSUE TITLE
Investigate why HA-proxy complains

### ISSUE THREAD

**Issue by abn** [victims/victims-production#1]
``` log
----------------------------------------
Exception happened during processing of request from ('$GEAR_ONE_IP', 19897)
Traceback (most recent call last):
  File "/var/lib/openshift/$UID/python/opt/lib/python2.7/SocketServer.py", line 284, in _handle_request_noblock
    self.process_request(request, client_address)
  File "/var/lib/openshift/$UID/python/opt/lib/python2.7/SocketServer.py", line 310, in process_request
    self.finish_request(request, client_address)
  File "/var/lib/openshift/$UID/python/opt/lib/python2.7/SocketServer.py", line 323, in finish_request
    self.RequestHandlerClass(request, client_address, self)
  File "/var/lib/openshift/$UID/python/opt/lib/python2.7/SocketServer.py", line 640, in __init__
    self.finish()
  File "/var/lib/openshift/$UID/python/opt/lib/python2.7/SocketServer.py", line 693, in finish
    self.wfile.flush()
  File "/var/lib/openshift/$UID/python/opt/lib/python2.7/socket.py", line 303, in flush
    self._sock.sendall(view[write_offset:write_offset+buffer_size])
error: [Errno 32] Broken pipe
----------------------------------------
```

**Comment by abn** [comment]
Raised this on openshift BZ. 

https://bugzilla.redhat.com/show_bug.cgi?id=991271

**Comment by abn** [comment]
The cartridge update is not yet online. Should be fixed when this is live.

The fix seems to only fix heartbeat checks. I can still see entries in the appserver.log file. Probably needs a bit more looking into.

**Comment by abn** [comment]
This seems to have gone away. Reopen if required.
