### ISSUE TITLE
SSL Certs

### ISSUE THREAD

**Issue by abn** [victims/victims-production#13]
```
[abn@bigmac ~]$ curl https://victi.ms
curl: (60) Unrecognized Object Identifier.
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```

**Comment by abn** [comment]
@dfj didn't we already add a proper cert?

**Comment by dfj** [comment]
I can't reproduce this problem, it is working fine with no error or warning for me. Please re-open if you can reproduce.

**Comment by abn** [comment]
@dfj this is still reproducible from multiple machines. Reopening.

**Comment by abn** [comment]
Python requests seems to indicate the cert is for *.rhcloud.com.

``` py
>>> import requests
>>> resp = requests.get('https://victi.ms')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 55, in get
    return request('get', url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 357, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python2.7/site-packages/requests/sessions.py", line 460, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python2.7/site-packages/requests/adapters.py", line 358, in send
    raise SSLError(e)
requests.exceptions.SSLError: hostname 'victi.ms' doesn't match either of '*.rhcloud.com', 'rhcloud.com'
```

**Comment by fweimer** [comment]
I suspect the missing intermediate certificate in the server's certificate message causes the original `curl` failure (that is, the error message is confusing).

**Comment by abn** [comment]
This is a duplicate of #15. Problem was traced as being an issue with the intermediate cert. Adding the satrcom one did not help.
