### ISSUE TITLE
Flask Caching keeps throwing KeyError

### ISSUE THREAD

**Issue by abn** [victims/victims-production#4]
The following is from the logs on stage when debugging.

``` py
Traceback (most recent call last):
  File "/var/lib/openshift/$UUID/python/virtenv/lib/python2.7/site-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/var/lib/openshift/$UUID/python/virtenv/lib/python2.7/site-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/var/lib/openshift/$UUID/python/virtenv/lib/python2.7/site-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/var/lib/openshift/$UUID/python/virtenv/lib/python2.7/site-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/var/lib/openshift/$UUID/python/virtenv/lib/python2.7/site-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/var/lib/openshift/$UUID/python/virtenv/lib/python2.7/site-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/var/lib/openshift/$UUID/python/virtenv/lib/python2.7/site-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/var/lib/openshift/$UUID/python/virtenv/lib/python2.7/site-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/var/lib/openshift/$UUID/app-root/data/victims-web/src/victims_web/blueprints/ui/__init__.py", line 73, in index
    return render_template('index.html', **get_data())
  File "/var/lib/openshift/$UUID/python/virtenv/lib/python2.7/site-packages/flask_cache/__init__.py", line 237, in decorated_function
    rv = self.cache.get(cache_key)
  File "/var/lib/openshift/$UUID/python/virtenv/lib/python2.7/site-packages/flask_cache/__init__.py", line 140, in cache
    return app.extensions['cache'][self]
KeyError: <flask_cache.Cache object at 0x28b3ad0>
```

**Comment by abn** [comment]
This was caused to a bad link command in the pre_start script.

Fixed in https://github.com/victims/victims-server-openshift/commit/a5b2876a06e67ab00d9ebf1f76866d9b5671f791
